const data1 = {
  data: {
    status: true,
    Message: "getPageFieldMappingList successfully",
    Data: [
      {
        ResourceKey: "SrfOrderColor",
        PageID: 47,
        MappingID: 320,
        ProductID: 2,
        Visible: true,
        Mandatory: false,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 3,
        DisplayText: "Color",
      },
      {
        ResourceKey: "StyleTypeID",
        PageID: 47,
        MappingID: 282,
        ProductID: 2,
        Visible: true,
        Mandatory: true,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 0,
        DisplayText: "Style Type",
      },
      {
        ResourceKey: "SpecQuantity",
        PageID: 47,
        MappingID: 440,
        ProductID: 2,
        Visible: true,
        Mandatory: true,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 4,
        DisplayText: "Quantity",
      },
      {
        ResourceKey: "DeliveryDate",
        PageID: 47,
        MappingID: 326,
        ProductID: 2,
        Visible: true,
        Mandatory: true,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 3,
        DisplayText: "Delivery Date",
      },
      {
        ResourceKey: "SrfOrderDate",
        PageID: 47,
        MappingID: 316,
        ProductID: 2,
        Visible: true,
        Mandatory: true,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 3,
        DisplayText: "Order Date",
      },
      {
        ResourceKey: "StockCount",
        PageID: 47,
        MappingID: 3123,
        ProductID: 2,
        Visible: true,
        Mandatory: false,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 0,
        DisplayText: "Count",
      },
      {
        ResourceKey: "SrfSizeClass",
        PageID: 47,
        MappingID: 292,
        ProductID: 2,
        Visible: true,
        Mandatory: false,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 0,
        DisplayText: "Size Class",
      },
      {
        ResourceKey: "SrfDate",
        PageID: 47,
        MappingID: 274,
        ProductID: 2,
        Visible: true,
        Mandatory: true,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 0,
        DisplayText: "Srf Date",
      },
      {
        ResourceKey: "SrfBuyerID",
        PageID: 47,
        MappingID: 278,
        ProductID: 2,
        Visible: true,
        Mandatory: false,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 0,
        DisplayText: "Buyer",
      },
      {
        ResourceKey: "SrfProtoNo",
        PageID: 47,
        MappingID: 284,
        ProductID: 2,
        Visible: true,
        Mandatory: false,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 0,
        DisplayText: "Proto No",
      },
      {
        ResourceKey: "MaterialSKULastID",
        PageID: 47,
        MappingID: 294,
        ProductID: 2,
        Visible: true,
        Mandatory: true,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 0,
        DisplayText: "Last",
      },
      {
        ResourceKey: "StockNo",
        PageID: 47,
        MappingID: 310,
        ProductID: 2,
        Visible: true,
        Mandatory: true,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 2,
        DisplayText: "StockNo",
      },
      {
        ResourceKey: "SrfArticle",
        PageID: 47,
        MappingID: 288,
        ProductID: 2,
        Visible: true,
        Mandatory: false,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 0,
        DisplayText: "Article",
      },
      {
        ResourceKey: "Article",
        PageID: 47,
        MappingID: 304,
        ProductID: 2,
        Visible: true,
        Mandatory: true,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 1,
        DisplayText: "Article",
      },
      {
        ResourceKey: "Color",
        PageID: 47,
        MappingID: 442,
        ProductID: 2,
        Visible: true,
        Mandatory: false,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 0,
        DisplayText: "Color",
      },
      {
        ResourceKey: "ConstructionID",
        PageID: 47,
        MappingID: 306,
        ProductID: 2,
        Visible: true,
        Mandatory: true,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 1,
        DisplayText: "Construction",
      },
      {
        ResourceKey: "SizeClassID",
        PageID: 47,
        MappingID: 308,
        ProductID: 2,
        Visible: true,
        Mandatory: true,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 1,
        DisplayText: "Size Class",
      },
      {
        ResourceKey: "Quantity",
        PageID: 47,
        MappingID: 322,
        ProductID: 2,
        Visible: true,
        Mandatory: true,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 3,
        DisplayText: "Quantity",
      },
      {
        ResourceKey: "SeasonID",
        PageID: 47,
        MappingID: 276,
        ProductID: 2,
        Visible: true,
        Mandatory: true,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 0,
        DisplayText: "Season",
      },
      {
        ResourceKey: "Status",
        PageID: 47,
        MappingID: 853,
        ProductID: 2,
        Visible: true,
        Mandatory: false,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 0,
        DisplayText: "Status",
      },
      {
        ResourceKey: "WidthID",
        PageID: 47,
        MappingID: 296,
        ProductID: 2,
        Visible: true,
        Mandatory: true,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 0,
        DisplayText: "Width",
      },
      {
        ResourceKey: "BuyerID",
        PageID: 47,
        MappingID: 300,
        ProductID: 2,
        Visible: true,
        Mandatory: true,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 1,
        DisplayText: "Buyer",
      },
      {
        ResourceKey: "GenderID",
        PageID: 47,
        MappingID: 302,
        ProductID: 2,
        Visible: true,
        Mandatory: true,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 1,
        DisplayText: "Gender",
      },
      {
        ResourceKey: "StyleStockID",
        PageID: 47,
        MappingID: 318,
        ProductID: 2,
        Visible: true,
        Mandatory: false,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 3,
        DisplayText: "StockNo",
      },
      {
        ResourceKey: "SrfProduct",
        PageID: 47,
        MappingID: 286,
        ProductID: 2,
        Visible: true,
        Mandatory: false,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 0,
        DisplayText: "Product",
      },
      {
        ResourceKey: "SrfNo",
        PageID: 47,
        MappingID: 272,
        ProductID: 2,
        Visible: true,
        Mandatory: false,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 0,
        DisplayText: "Srf No",
      },
      {
        ResourceKey: "SizeID",
        PageID: 47,
        MappingID: 438,
        ProductID: 2,
        Visible: true,
        Mandatory: true,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 4,
        DisplayText: "Size",
      },
      {
        ResourceKey: "SrfConstruction",
        PageID: 47,
        MappingID: 290,
        ProductID: 2,
        Visible: true,
        Mandatory: false,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 0,
        DisplayText: "Construction",
      },
      {
        ResourceKey: "SrfOrderNo",
        PageID: 47,
        MappingID: 314,
        ProductID: 2,
        Visible: true,
        Mandatory: false,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 3,
        DisplayText: "Srf Order No",
      },
      {
        ResourceKey: "ProtoNo",
        PageID: 47,
        MappingID: 298,
        ProductID: 2,
        Visible: true,
        Mandatory: true,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 1,
        DisplayText: "Proto No",
      },
      {
        ResourceKey: "ColorID",
        PageID: 47,
        MappingID: 312,
        ProductID: 2,
        Visible: true,
        Mandatory: true,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 2,
        DisplayText: "Color",
      },
      {
        ResourceKey: "SrfGenderID",
        PageID: 47,
        MappingID: 280,
        ProductID: 2,
        Visible: true,
        Mandatory: false,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 0,
        DisplayText: "Gender",
      },
      {
        ResourceKey: "ProductID",
        PageID: 47,
        MappingID: 4373,
        ProductID: 2,
        Visible: true,
        Mandatory: false,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 0,
        DisplayText: "Product",
      },
      {
        ResourceKey: "SampleTypeID",
        PageID: 47,
        MappingID: 324,
        ProductID: 2,
        Visible: true,
        Mandatory: true,
        Enable: true,
        SequenceOrder: null,
        SubPageID: 3,
        DisplayText: "Sample Type",
      },
    ],
  },
};
